from typing import Tuple, Optional, Dict, Any
from dataclasses import dataclass
import json
import logging
import math
import os
import re
import unicodedata
import urllib.request
from datetime import datetime, timedelta, timezone

logger = logging.getLogger(__name__)
from db import (
    get_admin_status_by_id, count_admin_couriers, count_admin_couriers_with_min_balance, get_setting,
    set_setting,
    increment_setting_counter,
    count_admin_allies, count_admin_allies_with_min_balance,
    get_api_usage_today, record_api_usage_event,
    get_api_usage_cost_summary,
    get_distance_cache, upsert_distance_cache,
    get_geocoding_text_cache, upsert_geocoding_text_cache, delete_geocoding_text_cache,
    delete_distance_cache_for_coord,
    set_ally_subscription_price, get_ally_subscription_price,
    create_ally_subscription, get_active_ally_subscription,
    expire_old_ally_subscriptions, get_ally_subscription_info, get_expiring_ally_subscriptions,
    upsert_scheduled_job, cancel_scheduled_job, mark_job_executed, get_pending_scheduled_jobs,
    get_recharge_request, insert_ledger_entry,
    get_admin_balance, update_admin_balance_with_ledger,
    register_platform_income,
    settle_route_additional_stops_fee,
    update_courier_link_balance, update_ally_link_balance,
    credit_welcome_balance,
    get_courier_link_balance, get_ally_link_balance,
    get_platform_admin,
    get_platform_sociedad_id,
    get_approved_admin_link_for_courier, get_approved_admin_link_for_ally,
    get_approved_admin_id_for_courier,
    get_eligible_couriers_for_order,
    upsert_reference_alias_candidate,
    list_reference_alias_candidates,
    get_reference_alias_candidate_by_id,
    review_reference_alias_candidate,
    set_reference_alias_candidate_coords,
    has_valid_coords,
    get_connection,
    P,
    DB_ENGINE,
    _row_value,
    SUPPORT_TYPE_DELIVERY_PIN,
    SUPPORT_TYPE_ROUTE_STOP_PIN,
    SUPPORT_TYPE_PICKUP_PIN,
    SUPPORT_TYPE_ROUTE_PICKUP_PIN,
    get_order_status_by_id,
    get_order_penalty_config,
    cancel_order,
    cancel_order_by_actor,
    republish_cancelled_order,
    cancel_route_by_actor,
    penalize_courier_for_delay_and_release,
    penalize_route_courier_for_delay_and_release,
    get_admin_by_telegram_id,
    get_ally_by_telegram_id,
    get_user_by_telegram_id,
    get_admin_by_user_id,
    can_admin_validate_references,
    get_courier_telegram_id,
    get_ally_telegram_id,
    get_admin_telegram_id,
    create_profile_change_request,
    has_pending_profile_change_request,
    list_pending_profile_change_requests,
    get_profile_change_request_by_id,
    mark_profile_change_request_approved,
    mark_profile_change_request_rejected,
    apply_profile_change_request_data,
    sync_all_courier_link_statuses,
    build_admin_invite_token,
    get_active_admin_invite_token,
    rotate_admin_invite_token,
    resolve_admin_invite_token,
    record_admin_invite_token_use,
    get_admin_invite_registrations,
    has_recent_invite_open,
    # Re-exports para que main.py no acceda a db directamente
    ensure_user,
    get_user_by_id,
    get_available_admin_teams,
    get_admin_rejection_type_by_id,
    get_ally_rejection_type_by_id,
    get_courier_rejection_type_by_id,
    get_admin_reset_state_by_id,
    get_ally_reset_state_by_id,
    get_courier_reset_state_by_id,
    enable_admin_registration_reset,
    enable_ally_registration_reset,
    enable_courier_registration_reset,
    clear_admin_registration_reset,
    clear_ally_registration_reset,
    clear_courier_registration_reset,
    admin_has_active_registration_reset,
    ally_has_active_registration_reset,
    courier_has_active_registration_reset,
    reset_admin_registration_in_place,
    reset_ally_registration_in_place,
    reset_courier_registration_in_place,
    list_approved_admin_teams,
    list_courier_links_by_admin,
    list_ally_links_by_admin,
    get_platform_admin_id,
    upsert_admin_ally_link,
    create_admin_courier_link,
    deactivate_other_approved_admin_courier_links,
    deactivate_other_approved_admin_ally_links,
    get_local_admins_count,
    create_ally,
    get_ally_by_user_id,
    get_pending_allies,
    get_ally_by_id,
    update_ally_status,
    update_ally_status_by_id,
    get_all_allies,
    update_ally,
    delete_ally,
    create_admin,
    user_has_platform_admin,
    get_all_admins,
    get_pending_admins,
    get_admin_by_id,
    update_admin_status_by_id,
    get_admin_by_team_code,
    update_admin_courier_status,
    upsert_admin_courier_link,
    create_ally_location,
    get_ally_locations,
    get_ally_location_by_id,
    get_default_ally_location,
    set_default_ally_location,
    update_ally_location,
    update_ally_location_coords,
    delete_ally_location,
    increment_pickup_usage,
    set_frequent_pickup,
    create_courier,
    get_courier_by_user_id,
    get_courier_by_id,
    get_courier_by_telegram_id,
    set_courier_available_cash,
    deactivate_courier,
    update_courier_live_location,
    set_courier_availability,
    expire_stale_live_locations,
    get_pending_couriers,
    get_pending_couriers_by_admin,
    get_pending_allies_by_admin,
    get_allies_by_admin_and_status,
    get_couriers_by_admin_and_status,
    update_courier_status,
    update_courier_status_by_id,
    get_all_couriers,
    update_courier,
    delete_courier,
    get_admin_link_for_courier,
    get_admin_link_for_ally,
    get_courier_link_balance,
    get_approved_admin_id_for_courier,
    create_order,
    set_order_status,
    assign_order_to_courier,
    get_order_by_id,
    add_order_incentive,
    add_route_incentive,
    update_order_payment,
    get_orders_by_ally,
    get_ally_orders_between,
    get_ally_routes_between,
    get_orders_by_courier,
    get_courier_daily_earnings_history,
    get_courier_earnings_by_date,
    get_courier_earnings_between,
    get_totales_registros,
    add_courier_rating,
    get_active_terms_version,
    has_accepted_terms,
    save_terms_acceptance,
    save_terms_session_ack,
    create_ally_customer,
    update_ally_customer,
    archive_ally_customer,
    restore_ally_customer,
    get_ally_customer_by_id,
    get_ally_customer_by_phone,
    list_ally_customers,
    search_ally_customers,
    create_customer_address,
    update_customer_address,
    archive_customer_address,
    restore_customer_address,
    get_customer_address_by_id,
    list_customer_addresses,
    increment_ally_customer_usage,
    increment_customer_address_usage,
    find_matching_customer_address,
    update_customer_address_coords,
    PARKING_FEE_AMOUNT,
    set_address_parking_status,
    get_addresses_pending_parking_review,
    get_all_addresses_parking_review,
    get_ally_parking_fee_enabled,
    toggle_ally_parking_fee,
    get_ally_telegram_id_by_address_id,
    get_ally_telegram_id_by_ally_id,
    get_last_order_by_ally,
    get_recent_delivery_addresses_for_ally,
    get_link_cache,
    upsert_link_cache,
    get_all_approved_links_for_courier,
    get_all_approved_links_for_ally,
    ensure_platform_temp_coverage_for_ally,
    create_recharge_request,
    list_pending_recharges_for_admin,
    list_all_pending_recharges,
    get_admins_with_pending_count,
    list_recharge_ledger,
    get_admin_payment_info,
    update_admin_payment_info,
    update_recharge_proof,
    create_payment_method,
    get_payment_method_by_id,
    list_payment_methods,
    toggle_payment_method,
    deactivate_payment_method,
    get_admin_reference_validator_permission,
    set_admin_reference_validator_permission,
    # Re-exports rutas multi-parada
    create_route,
    create_route_destination,
    get_route_by_id,
    get_active_routes_by_ally,
    get_route_destinations,
    get_pending_route_stops,
    reorder_route_destinations,
    update_route_status,
    assign_route_to_courier,
    deliver_route_stop,
    cancel_route,
    create_route_offer_queue,
    get_next_pending_route_offer,
    mark_route_offer_as_offered,
    mark_route_offer_response,
    get_current_route_offer,
    delete_route_offer_queue,
    reset_route_offer_queue,
    get_all_online_couriers,
    get_active_orders_without_courier,
    block_courier_for_ally,
    unblock_courier_for_ally,
    get_blocked_courier_ids_for_ally,
    set_courier_arrived,
    set_route_courier_arrived,
    set_courier_accepted_location,
    get_active_order_for_courier,
    get_active_orders_for_courier,
    get_active_route_for_courier,
    get_courier_delivery_time_stats,
    get_all_local_admins,
    # Re-exports admin_locations
    create_admin_location,
    get_admin_locations,
    get_admin_location_by_id,
    get_default_admin_location,
    set_default_admin_location,
    increment_admin_location_usage,
    archive_admin_location,
    update_admin_location,
    create_admin_customer,
    update_admin_customer,
    archive_admin_customer,
    restore_admin_customer,
    get_admin_customer_by_id,
    get_admin_customer_by_phone,
    list_admin_customers,
    search_admin_customers,
    create_admin_customer_address,
    update_admin_customer_address,
    archive_admin_customer_address,
    restore_admin_customer_address,
    get_admin_customer_address_by_id,
    list_admin_customer_addresses,
    increment_admin_customer_usage,
    increment_admin_customer_address_usage,
    # Re-exports offer queue
    clear_offer_queue,
    # Re-exports order_support_requests
    create_or_get_pending_support_request,
    create_order_support_request,
    get_pending_support_request,
    resolve_support_request,
    cancel_route_stop,
    list_pending_support_requests,
    get_all_pending_support_requests,
    get_support_request_full,
    get_all_orders,
    get_admin_panel_balances_data,
    get_admin_panel_users_data,
    get_admin_panel_earnings_data,
    get_admin_balance_breakdown,
    get_admin_ledger_movements,
    get_admin_saldo_hoy,
    # Re-exports plantillas de pedidos admin
    save_order_template,
    list_order_templates,
    get_order_template_by_id,
    increment_order_template_usage,
    delete_order_template,
    # Re-exports pedidos especiales admin y couriers excluidos
    get_admin_special_orders_between,
    get_admin_special_orders_recent,
    get_order_excluded_couriers,
    reset_order_excluded_couriers,
    add_order_excluded_courier,
    create_pending_fee_collection,
    resolve_pending_fee_collection,
    get_pending_fee_collection,
    get_all_pending_fee_collections,
    get_platform_sociedad,
    get_platform_sociedad_id,
    transfer_sociedad_to_platform,
    get_sociedad_balance,
    get_sociedad_saldo_hoy,
    get_dashboard_stats_data,
    # Re-exports web_users (panel web multiusuario)
    create_web_user,
    get_web_user_by_username,
    get_web_user_by_id,
    get_web_user_by_courier_id,
    get_web_user_by_admin_id,
    list_web_users,
    update_web_user_status,
    update_web_user_password,
    get_telegram_id_for_web_user,
    ensure_web_admin,
    # Re-exports ally_form_requests (enlace público del aliado)
    get_or_create_ally_public_token,
    get_ally_by_public_token,
    create_ally_form_request,
    get_ally_form_request_by_id,
    update_ally_form_request_status,
    mark_ally_form_request_converted,
    list_ally_form_requests_for_ally,
    update_ally_delivery_subsidy,
    update_ally_min_purchase_for_subsidy,
    count_ally_form_requests_by_status,
    # Re-exports recarga directa por plataforma
    get_all_active_couriers,
    get_all_active_allies,
    get_all_local_admins_approved,
    # Re-exports suscripciones
    get_expiring_ally_subscriptions,
)

ADMIN_INVITE_START_PREFIX = "inv_"
ADMIN_INVITE_USER_DATA_KEY = "admin_invite_token"

# ... (el resto del contenido de services.py, incluyendo approve_role_registration, audit_admin_invite_event, build_order_pricing_breakdown) ...
